"""Create initial database schema

Revision ID: 2b4f25e11063
Revises:
Create Date: 2025-06-28 17:22:23.794168

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2b4f25e11063'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
